config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_save :update_counter

  private

  def update_counter
    post.increment!(:comments_counter)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.author = current_user
    if @comment.save
      redirect_to user_post_path(current_user.id, @post.id), notice: 'You created a comment!'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text, :post_id, :user)
  end
end

app/views/comments/new.html.erb
<%= form_with model: @comment, url: user_post_comments_path(post_id: @post.id), scope: :comment do |form| %>
  <b>Add a comment:</b>
  <div>
    <%= form.text_area :text, placeholder:"Leave a comment here", id:"comment" %>
    <label for="comments">Comment</label>
  </div>
  <div>
    <%= form.submit "Add comment" %>
  </div>
<% end %>