config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  ##
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  attribute :post_counter, default: 0
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'
  validates :name, presence: true
  validates :post_counter, numericality: { greater_than_or_equal_to: 0 }

  def last_3_posts
    posts.includes(:author).order(created_at: :desc).limit(3)
  end

  def is?(requested_role)
    role == requested_role.to_s
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find_by(id: params['id'])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end

  def edit
    @user = User.find_by(id: params['id'])
  end

  def update
    @user = User.find_by(id: params['id'])
    @user.update(user_params)
    redirect_to users_path
  end

  def destroy
    @user = User.find_by(id: params['id'])
    @user.destroy
    redirect_to users_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_avatar(url)
    if url.present?
      image_tag(url, alt: 'rss feed', class: 'user-img')
    else
      image_tag('https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_640.png',
                alt: 'rss feed', class: 'user-img')
    end
  end
end

app/views/users/index.html.erb
<h2 class = 'user-container container'>Bloggers on Rails</h2><br>
<ul class = 'user-container container'>
  <% @users.each do |user| %>
    <li class='user'> 
      <%= link_to user_avatar(user.photo), user_path(user) %> 
      <div class ='user-details'>
        <h2 class ='user-name'> <%= link_to user.name, user_path(user) %> </h2>
        <p class = 'user-counter'> Number of posts: <%= link_to user.post_counter, user_path(user) %> </p>
      </div>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<p> new user </p>

app/views/users/show.html.erb
<section class = 'user-container container'>
<div class='user'>
  <%= link_to user_avatar(@user.photo), user_path(@user), class: 'user-image' %>
  <div class = 'user-details'>
    <h2 class ='user-name'><%= @user.name %></h2> 
    <p class = 'user-counter'> number of posts: <%= @user.post_counter %></p>
  </div>
</div>


<div class='user-bio'>
  <h3>Bio</h3>
  <p> <%= @user.bio %></p>
</div>

<ul class='post'>
  <% @user.last_3_posts.each do |post| %>
  <li class='post-details'>
    <h3><a class="post-title" role="button" href="<%= user_post_path(@user, post) =%>"><%= post.title =%></a></h3>
    <p class='post-text'> <%= post.text*10 %> </p>
    <p class='post-counter user-counter'> 
      &#128172 <%= post.comments_counter %>   
      &#10084 <%= post.likes_counter %> 
    </p>
  </li>
  <% end %>
</ul>
<div style="display: flex; justify-content: center">
  <a class="btn btn-primary" type="button" href="<%= user_posts_path(@user) %>">See all posts</a>
</div>
</section>