config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts do
      resources :comments
      resources :likes, only: [:create, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogOnRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="navbar navbar-light bg-warning ">
      
        <h1> <%= link_to "BlogOnRails", root_path, class:"custom-link" %> </h1>
        <div class="d-flex p-3">
          <% if user_signed_in? %>
            <%= link_to "+New Post", new_user_post_path(current_user), class: "btn m-1 custom-link" %>
            <%= link_to "Profile", edit_user_registration_path, class: "btn m-1 custom-link" %>
            <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-dark m-1 custom-link" %>
          <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "m-1 custom-link" %>
            <%= link_to "Sign Up", new_user_registration_path, class: "m-1 custom-link" %>

          <% end %>
        </div>
        
    </header>
    <div class="bg-warning hello">
          <% if user_signed_in? %>
            
          <% else%>
            <h2>Stay Curious.</h2>
            <p>Discover stories, thinking, and resources <br> to help you become a better developer.</p>
            <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-dark m-1 custom-link btn-hello" %>
          <% end %>
        </div>
     <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>